# -*- coding: utf-8 -*-
# This file is part of Python Cielo Webservice.
#
# Copyright (c) 2016, Rockho Team. All rights reserved.
# Author: Christian Hess
#
# This source code is licensed under the AGPLv3 license found in the
# LICENSE file in the root directory of this source tree.


class CieloPaymenType(object):
    CreditCard = "CreditCard"


class CieloCardBrand(object):
    Visa = "Visa"
    Mastercard = "Mastercard"
    Amex = "Amex"
    Elo = "Elo"
    Auria = "Auria"
    JCB = "JCB"
    Diners = "Diners"
    Discover = "Discover"


class CieloPaymentInterest(object):
    ByMerchant = "ByMerchant"
    

class CieloPaymentCurrency(object):
    BRL = "BRL"
    USD = "USD"
    MXN = "MXN"
    COP = "COP"
    CLP = "CLP"
    ARS = "ARS"
    PEN = "PEN"
    EUR = "EUR"
    PYN = "PYN"
    UYU = "UYU"
    VEB = "VEB"
    VEF = "VEF"
    GBP = "GBP"


class CieloJSONObject(object):

    '''
    Cielo JSON compatible object model.
    Cielo base object models must override this class,
    to be able to be instantiated from a valid Cielo JSON dictionary.
    '''

    _errors = []

    class Meta:
        required = []

    def __init__(self, json):
        '''
        Initialize the instance populating attributes 
        with the given Cielo JSON data from ´json´

        :param json: Cielo REST JSON as a dictionary
        :type json: dict  
        '''
        self.from_json(json)
        self.validate()

    def from_json(cls, json):
        '''
        Populates the attributes with the given Cielo JSON data

        :param json: Cielo REST JSON as a dictionary
        :type json: dict  
        '''
        raise NotImplementedError("Implement this method.")

    def to_json(self):
        '''
        Returns this object as a JSON dictionary to be used on requests
        '''
        raise NotImplementedError("Implement this method.")

    def validate(self):
        '''
        Validates this object.
        Errors can be fetch through `errors` attribute.
        :rtype: bool
        :return: wheter this object is valid or not
        '''
        raise NotImplementedError("Implement this method.")

    @property
    def errors(self):
        '''
        Returns the errors generated by the `validate` method
        as a list os named tuples (K, V) where K is the
        attribute with error and V is the error itself
        '''
        return self._errors


class CieloCustomerAddress(CieloJSONObject):
    street = ''
    number = ''
    complement = ''
    zip_code = ''
    city = ''
    state = ''
    country = ''


class CieloCustomer(CieloJSONObject):
    name = ''
    email = ''
    birth_date = ''
    identity = ''
    identity_type = None
    address = None
    delivery_address = None


class CieloRequestCreditCard(CieloJSONObject):
    card_number = ''
    holder = ''
    expiration_date = ''
    security_code = ''
    brand = None
    save_card = False


class CieloResponseCreditCard(CieloJSONObject):
    card_number = ''
    holder = ''
    expiration_date = ''
    security_code = ''
    brand = None
    save_card = False
    card_token = ''


class CieloResponsePaymentLink(CieloJSONObject):
    method = ''
    rel = ''
    href = ''


class CieloRequestPayment(CieloJSONObject):
    payment_type = None
    credit_card = None
    amount = 0
    currency = ''
    country = ''
    provider = ''
    service_tax_amount = 0
    installments = 0
    interest = None
    capture = False
    authenticate = False
    soft_descriptor = ''
    

class CieloResponsePayment(CieloJSONObject):
    service_tax_amount = 0
    installments = 0
    interest = ''
    capture = False
    authenticate = False
    credit_card = None
    proof_of_sale = ''
    tid = ''
    authorization_code = ''
    payment_id = ''
    payment_type = None
    currency = ''
    country = ''
    extra_data_collection = []
    status = 0
    return_code = ''
    return_message = ''
    links = []
    amount = 0
    captured_amount = 0



class CieloResponse(CieloJSONObject):
    merchant_order_id = ''
    customer = None
    payment = None

